.gitignore, click_repl/__init__.py
- added .gitignore support for intellij based projects (generated with the intellij ignore plugin)
- a bit more PEP8 compliance (minor styling)
- using prompt instead of get_input (deprecated)
- fixed the message prompt to be a unicode (would crash on Python 2.7.x with an assertion error)
=> fix AssertionError due to non-unicode prompt on python 2.7.x

click_repl/__init__.py, click_repl/exceptions.py, setup.py
add six as an explicit dependency for Py2 / 3 compatibility (already part of prompt_toolkit)
=> internal click-repl commands (exit / general help for repl usage)

click_repl/__init__.py
This commit fixes the issue with tab completion of nested commands described in #13.
To give an example of what the original issue this fixes is, consider the simple Click CLI using click-repl in https://gist.github.com/BobWhitelock/184e0669c4d76f42f85b674bf9236b69.
Previously with this CLI, while in the REPL, if you enter the following:
```
> first_level_command <tab>
```
no completions would be given, and you would have to start entering part of the next level of commands to get some completions shown.
With this commit, completions are now shown in the above situation without needing to start entering anything.
Thanks!
=> Fix tab completion of nested commands (fixes #13)

README.rst
This section documents how you can have more flexibility over your `click-repl` prompt, using the existing functionality of `click-repl`.
This resolves #18 as it documents how the requested feature can already be implemented.
=> Document passing `prompt_kwargs`

click_repl/__init__.py
This PR contains a couple of small tweaks to `click-repl` to better support my use case (while preserving the current default behaviour) and to fix what doesn't seem useful behaviour to me, allowing the creation of nested REPLs. See the individual commits for full details.
I'm happy to make further changes to this if you think any are needed before merging.
Thanks!
=> Miscellaneous fixes and improvements

click_repl/__init__.py
fixes #27. outputs an error message to the user and continues the loop.
=> don't die on unmatched quotes

click_repl/__init__.py
This fixes #24 by adding a click_repl.exit() command and triggering
an exit when ExitReplException is hit.
=> Allow ExitReplException to exit the repl

README.rst
I took the example code as "how you run a click-repl app", and was confused when the examples didn't work at all.  I figured it out for the 'advanced usage' example, but when I read the initial example of how to use `register_repl` I assumed that that replaced the `cli()` call.
Of course, it doesn't.  The fact that `register_repl` only _registers the repl_ command is implied by the name, but for such a small example snippet, where everything else needed to function is included, not including the `cli()` line implied to me that it wasn't necessary.  
This update just makes the `cli()` call explicit in both examples, and hopefully nobody else will suffer from my confusion.
Related issue: #44
=> add cli call to README examples

click_repl/__init__.py
First we attempt import of `click.exceptions.Exit`, but if it doesn't exist we polyfill with a local exception class `ClickExit` (that will never be thrown, of course).
Test approach:
- Manually tested using the example code in click-contrib/click-repl#50.
- Tested against python 2.7.15 and 3.7.0
- Tested against Click 6.7 and 7.0.
Fixes click-contrib/click-repl#47
Fixes click-contrib/click-repl#50
=> Handle click.exceptions.Exit, introduced in Click 7.0

.travis.yml, scripts/runtox.sh, tox.ini
This is a more experimental change. There's a library called [tox-travis](https://github.com/tox-dev/tox-travis) that seems to do the same thing as the `runtox.sh` script. I wanted to submit a PR to see if it does the right thing, but keep it separate from my other test PR.
=> Use tox-travis instead of custom runtox script

tests/test_argument.py, tests/test_basic.py, tests/test_command_collection.py
This fixes tests with click 7.0, which now converts underscores to hyphens in command names. If you have any suggestions for how to have different expectations in 6.0 vs 7.0, let me know.
You can see the commit that changed this behavior here: pallets/click@5d1df0e042b2f8b0dee8f6dd9ce74edce331a950
=> Update tests to expect hyphens

click_repl/__init__.py
simple migration from `_bashcomplete` to `shell_completion`. Fixes #72.
=> support for click 8 completion changes

click_repl/__init__.py
Even the simplest example from the README.rst leads to unbound memory usage growth in my environment.
Instead of using the prompt() function from prompt_toolkit.shortcuts, I propose to use the prompt() method from the PromptSession() class.
=> Fix unbound memory usage growth when using prompt() function

click_repl/__init__.py, setup.cfg, tests/test_basic.py
Changes done in this branch:
- Merged code with PR #65
- Added ignore C901 for flake8 (or else, the PR will fail, for the reason that `ClickCompleter.get_completions` is too complex)
- Added test cases for hidden command & options in tests/test_basic.py
=> Added filter for hidden commands and options

click_repl/__init__.py, tests/test_command_collection.py
I've merged the PR #62, though still to test its actual functionality, it should be done in the command line, but I've still included some test cases for checking the auto completion for those subcommands
Solves: #58
=> Merged PR #62: Pass top-level args to subcommand invocation

click_repl/_completer.py, tests/test_command_collection.py, tests/test_completion/test_path_type/test_path_type.py
This feature expands environment variables in a path argument
This feature is only available for path type argument/options
This feature must be implemented for every other argument types as well
=> Added 'expand environmental variables in path' feature

click_repl/_repl.py, tests/test_repl.py
I've added three tests:
- One demonstrates that subcommands work with repl() - there was no such test.
- The other two demonstrates the issue documented in #92. 
Not sure yet on how to make them pass, welcoming any ideas.
=> Fix for issue #92

click_repl/_completer.py, tests/test_completion/test_common_tests/test_option_completion.py
Change only applied for options with `multiple=False`.
```sh
> cmd <TAB>
--foo
--bar
> cmd --foo t <TAB>
--foo
--bar
```
```sh
> cmd <TAB>
--foo
--bar
> cmd --foo t <TAB>
--bar
```
=> Hide already used (non-`multiple`) options

click_repl/_completer.py, tests/test_completion/test_common_tests/test_option_completion.py
When completing option values, only values corresponding to the option being completed should be shown.
Following exemples are based on a command looking like this:
```py
@click.command()
@click.option('-a', type=click.Choice(['a_val1', 'a_val2']))
@click.option('-b', type=click.Choice(['b_val1', 'b_val2']))
def cli():
pass
```
```sh
> cmd -a <TAB>
a_val1
a_val2
b_val1
b_val2
```
```sh
> cmd -a <TAB>
a_val1
a_val2
```
=> Fix values shown for wrong option

click_repl/_completer.py, tests/test_completion/test_common_tests/test_option_completion.py
The `ClickCompleter` can now receive a `shortest_only` keyword argument.
If set to `True`, only the shortest version of each option will be shown by default (ie. if we keep pressing `Tab` & `Space`).
```sh
> cmd <TAB>
--verbose
-v
> cmd -<TAB>
--verbose
-v
```
```sh
> cmd <TAB>
-v
> cmd -<TAB>
--verbose
-v
```
=> Add a `shortest_only` option

click_repl/__init__.py, click_repl/_completer.py, click_repl/_ctx_stack.py, click_repl/_repl.py, click_repl/core.py, click_repl/globals_.py, setup.cfg, tests/test_repl_ctx.py
This class is very much similar to `click.Context` class, which keeps track of every layer of nested group and chained command invocations are to be done, based on the input from the prompt, while having link with their parent context
But this class is used to do the same but keeps track of each layer of REPL session in a nested layer of REPL sessions.
In this PR:
The construction of `PromptSession` object is moved into `ReplContext`'s `__init__` method and stored as one of the context object's attributes. So that it'll be invoked only if the REPL is invoked in a proper terminal window, rather than via piping in shell.
This class also allows users to change prompt text of the REPL at runtime, and also keep track of the command's history.
These are some of the features that I have manually …
=> Added ReplContext class
